### ISSUE TITLE
vagrant issue

### ISSUE THREAD

**Issue by ShingankarAbhijeet** [kodekloudhub/certified-kubernetes-administrator-course#139]
Not able to find the private keys to vagrant VMs to connect to. this was present earlier under certified-kubernetes-administrator-course\.vagrant\machines\kubemaster\virtualbox seems to be removed or replaced. needed help in setting up the cluster for kubeadm practice.

**Comment by msguit** [comment]
certified-kubernetes-administrator-course/kubeadm-clusters/virtualbox/.vagrant/machines/kubemaster/virtualbox is the correct one. I just recently installed it on my Mac and it works. Priv key can be found there.

**Comment by fireflycons** [comment]
Seems you sorted it out so I'll close this

Remember you can simply run `vagrant ssh` with the VM name and it will connect you directly as the `vagrant` user without requiring the keys.
