### ISSUE TITLE
Lacture request for certified-kubernetes-administrator-with-practice-tests

### ISSUE THREAD

**Issue by xyzkpz** [kodekloudhub/certified-kubernetes-administrator-course#149]
Hi Sir,Maam

i have purchase the [Certified Kubernetes Administrator (CKA) with Practice Tests] on udemy
(https://www.udemy.com/course/certified-kubernetes-administrator-with-practice-tests/)

in which i have found from official doc current Kubernetes version is V1.28 
(Kubernetes v1.28)
(https://v1-28.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)  

![image](https://github.com/kodekloudhub/certified-kubernetes-administrator-course/assets/57756712/e85d5e54-f4ad-4719-a4cb-d7d78328bd00)

but on udemy course is updated till to V1.27. 
![image](https://github.com/kodekloudhub/certified-kubernetes-administrator-course/assets/57756712/2812f919-e1b0-4fa2-895f-73a20d04e527)

please check and update the course if there is any update in this course.

Thanks Regards 
kkishanppanchal@gmail.com

**Comment by fireflycons** [comment]
Hello @xyzkpz 

There are no changes in v1.28 (or for that matter v1.29) that affect the course content. The changes that are in these versions are outside the scope of the course curriculum therefore you need not worry.

Please note that you should use the [community forum](https://community.kodekloud.com/) to raise such questions. They will be answered faster.
