### ISSUE TITLE
Video content and picture for Kube proxy is wrong

### ISSUE THREAD

**Issue by 111andre111** [kodekloudhub/certified-kubernetes-administrator-course#18]
On this page is a graphics how kube-proxy works
https://github.com/kodekloudhub/certified-kubernetes-administrator-course/blob/master/docs/02-Core-Concepts/09-Kube-Proxy.md

As well in the video content at around minute 2:47min.

This graphics has wrong IP addresses, as the service has `10.96.0.12` IP but pod at left side has `10.32.0.14` and on right side has `10.32.0.15` .

So the one on the left side is wrong as it shows 10.32.0.15 but it should be 14

**Comment by fireflycons** [comment]
Closed /stale
