### ISSUE TITLE
Instructions for upgrading k8s cluster are wrong

### ISSUE THREAD

**Issue by csheremeta** [kodekloudhub/certified-kubernetes-administrator-course#38]
The instructions in https://github.com/kodekloudhub/certified-kubernetes-administrator-course/blob/master/docs/06-Cluster-Maintenance/05-Cluster-Upgrade-Introduction.md are incorrect. Many of the commands do not work, and the master components are no longer run as services.

**Comment by fireflycons** [comment]
Closed /stale
