### ISSUE TITLE
Some errors in Practice Test Role Based Access Controls

### ISSUE THREAD

**Issue by schollii** [kodekloudhub/certified-kubernetes-administrator-course#47]
In step 10 of _Role Based Access Controls_ practice test, it says 

> The dev-user is trying to get details about the dark-blue-app pod in the blue namespace. Investigate and fix the issue.
> 
> We have created the required roles and rolebindings, but something seems to be wrong.

However that namespace does not exist, yet alone have the role + rb. I tried the scenario about 3 times, did this each time. This was first week of Dec, roughly. 

I looked in a few of the usual folders where some of the yaml is stored such as /var/ and /opt but did not see any. 

BTW I was able to complete the question by creating the namespace, role, and rolebinding, and guessing the correct role requirements. 

There was an earlier step (perhaps step 5 or 6) in same test that a smaller issue, saying that a user had been created and to check out the corresponding info... but the role did not exist. Luckily that question was multiple choice (actually just 2 choices) so it was easy to complete it. 

The final step, 11, had possibly a minor issue in that it said that the API group should be `apps` and `extensions`, whereas it only needs to be one of those 2: the one that pertains to the version of kubernetes being used. 

Note: I submitted email about this to support@kodekloud and heard back that this is being looked after, but I since found out I could submit issues here, which makes more sense since technically I'm reporting a problem not asking for support :)

**Comment by axelgMS** [comment]
+1

**Comment by fireflycons** [comment]
Many labs have been updated since this time.
If you still have issues,. please report them here https://kodekloud.com/community/c/kubernetes/6
Thanks
