### ISSUE TITLE
Practice Test KubeConfig - servers are not well-defined in the kube-config file - KUBE_ADDRESS

### ISSUE THREAD

**Issue by axelgMS** [kodekloudhub/certified-kubernetes-administrator-course#52]
in the kube-config file:

**- cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: KUBE_ADDRESS
  name: test-cluster-1**

and running "kubectl get pods" gives:
**controlplane $ kubectl get pods
Unable to connect to the server: dial tcp: lookup KUBE_ADDRESS on 8.8.8.8:53: no such host**

**Comment by hw038** [comment]
you should check "server: " origin config file (ex, https://172.17.0.20:6443)

answer is server: https://172.17.0.20:6443
