### ISSUE TITLE
Windows 10 issues

### ISSUE THREAD

**Issue by g0pinath-metricon** [kodekloudhub/certified-kubernetes-administrator-course#7]
Hello Team - I got the error  "vagrant@127.0.0.1: Permission denied (publickey)." and it got solved with below env var.

Resolved with set VAGRANT_PREFER_SYSTEM_BIN=0

Also, I had my RTFM moment with installing vagrant due to hyper-v, if you could capture these in pre-req section it will save time others if they run into this. Most people having windows 10 laptop and taking k8s course will have docker installed which will need Hyper-v component. Anyone trying this lab will run into this issue if they didnt read the document for Vagrant which says to remove Hyper-V

Thanks
Gopinath T

**Comment by fireflycons** [comment]
All the build your own cluster instructions are refreshed.
https://github.com/kodekloudhub/certified-kubernetes-administrator-course/tree/master/kubeadm-clusters
