### ISSUE TITLE
LAB - kubeadm init doesn't work well

### ISSUE THREAD

**Issue by axelgMS** [kodekloudhub/certified-kubernetes-administrator-course#77]
Section 11 - installing kubernetes the kubeadm way

In the lab, the following command doesn't work well - even with my IP...

**_kubeadm init --apiserver-cert-extra-sans=controlplane --apiserver-advertise-address 10.2.223.3 --pod-network-cidr=10.244.0.0/16_**

I have:

> _ifconfig eth0
> eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
>         inet 10.187.196.6  netmask 255.255.255.0  broadcast 10.187.196.255_

and so I run :

> _root@controlplane:~# kubeadm init --apiserver-advertise-address=10.187.196.6   --apiserver-cert-extra-sans=controlplane --pod-network-cidr=10.244.0.0/16_

which gives me:

> [wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
> [kubelet-check] Initial timeout of 40s passed.
> [kubelet-check] It seems like the kubelet isn't running or healthy.
> [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
> [kubelet-check] It seems like the kubelet isn't running or healthy.
> [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
> [kubelet-check] It seems like the kubelet isn't running or healthy.
> [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
> [kubelet-check] It seems like the kubelet isn't running or healthy.
> [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
> [kubelet-check] It seems like the kubelet isn't running or healthy.
> [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
> 
>         Unfortunately, an error has occurred:
>                 timed out waiting for the condition
> 
>         This error is likely caused by:
>                 - The kubelet is not running
>                 - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
> 
>         If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
>                 - 'systemctl status kubelet'
>                 - 'journalctl -xeu kubelet'
> 
>         Additionally, a control plane component may have crashed or exited when started by the container runtime.
>         To troubleshoot, list all containers using your preferred container runtimes CLI.
> 
>         Here is one example how you may list all Kubernetes containers running in docker:
>                 - 'docker ps -a | grep kube | grep -v pause'
>                 Once you have found the failing container, you can inspect its logs with:
>                 - 'docker logs CONTAINERID'
> 
> error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
> To see the stack trace of this error execute with --v=5 or higher

[init] Using Kubernetes version: v1.22.0

**Comment by axelgMS** [comment]
Note that this lab is using the new experience (Beta). Not sure if that can have an impact ?

But there's no way to avoid using that new lab experience

**Comment by M-Ayman** [comment]
it is working fine. Can you check it again from your side?
