### ISSUE TITLE
Question: What the difference set the node's address as loopback and its local ethernet ip?

### ISSUE THREAD

**Issue by flavono123** [kodekloudhub/certified-kubernetes-administrator-course#88]
https://github.com/kodekloudhub/certified-kubernetes-administrator-course/blob/master/ubuntu/vagrant/setup-hosts.sh#L5

Above provisioning codes do it like:
```
# /etc/hosts

# change from 
# 127.0.1.1	cluster1-master1	cluster1-master1
# to
10.0.2.15 cluster1-master1 cluster1-master1.local
```

What the difference of the cluster1-master1 is as 127.0.1.1 and as 10.0.2.15 **in the local**?
+) What the meaning of duplication domain for the same IP? (`127.0.1.1 cluster1-master1 cluster1-master1`)

**Comment by fireflycons** [comment]
All the cluster build instructions in this repo have since been refreshed and updated.
