### ISSUE TITLE
404 on opening Service networking page - CKA - github

### ISSUE THREAD

**Issue by chinnappa-raju** [kodekloudhub/certified-kubernetes-administrator-course#92]
Service networking page does not load the content. Getting error 404. 

![ServiceNetworking-page](https://user-images.githubusercontent.com/44596386/179342841-cca7efbb-f280-4648-875a-0134203df693.png)

**Comment by Tej-Singh-Rana** [comment]
Hi Chinnappa-raju,
This issue has been resolved.

Thanks & Regards,
