### ISSUE TITLE
Vagrant Issue

### ISSUE THREAD

**Issue by norod-boop** [kodekloudhub/certified-kubernetes-administrator-course#93]
I am getting following error:
![image](https://user-images.githubusercontent.com/62235761/182603160-579197be-7fa8-4388-bef0-96315f8731cf.png)
 
Does someone know how to solve this? 
I am working on Windows.
Kind regards.

**Comment by LtKao** [comment]
I faced the same issue. I was working on centOS VM on VMware. It gave virtualization issue when vagrant issues virtualbox commands. Virtualization inside virtualization.

Shift to **Visual studio**

**Comment by mikenhan** [comment]
`  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end`

I added this within the `Vagrant.configure` section and it worked for me.

**Comment by fireflycons** [comment]
Note that all the cluster build instructions were updated in March 2024.
They have been tested on Windows, Intel Mac and Apple Silicon.
They are all targeted at Ubuntu VMs. The vagrant file is not tested with CentOS.
